version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: url-shortener-app
    environment:
      DATABASE_DSN: "host=postgres user=postgres password=postgres dbname=url_shortener port=5432"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
